class node:
    # node is a basic block 
    instructions = [] # list of instructions forming the basic block
    label = None # TODO label of the basic block (address of the label)
    ID="" # generated by the tool for each node in each subgraph  
    edges_out = [] # list of edges leaving the basic block
    edges_in = [] # list of edges entering the basic block
    # they are needed only to concatenate the subgraphs from the tool
    is_entry = False # is the node entry of a function
    is_exit = False # is the node exit of a function
    function_name = None 
    function_id = None 
    vulnerable = False
    vulns_IDs= [] # list of IDs of vulnerabilities in the function which this node belongs to

    def __init__(self, id, label, is_entry, is_exit,edges_in, edges_out,instructions):
        self.ID =id #TODO remove this
        self.label = label
        self.is_entry = is_entry
        self.is_exit = is_exit
        self.edges_in = edges_in
        self.edges_out = edges_out
        self.instructions = instructions
    
    def get_node_dict(self):
        node_dict=dict()
        node_dict["ID"]=self.ID
        node_dict["label"]=self.label
        node_dict["is_entry"]=self.is_entry
        node_dict["is_exit"]=self.is_exit
        node_dict["instructions"]=self.instructions
        node_dict["function_name"]=self.function_name
        node_dict["function_id"]=self.function_id
        node_dict["vulnerable"]=self.vulnerable
        node_dict["vulns_IDs"]=self.vulns_IDs
        node_dict["edges_out"]=[]
        for edge in self.edges_out:
                node_dict["edges_out"].append(edge.get_edge_dict())
        return node_dict
    def add_edges_out(self, edge):
        self.edges_out.append(edge)
    def add_edges_in(self, edge):
        self.edges_in.append(edge)
  