import json


cves = \
{
'252': "null dereference|Unchecked Return Value" ,
'392' :"null dereference",
'393' :"null dereference",
'476': "null dereference|NULL Pointer Dereference",
'826': "null dereference|use after lifetime",
'908': "null dereference",
'824' :"uninitialized value",
'772' :"memory leak|use after lifetime",
'911' :"memory leak",
'1045': "memory leak",
'563' :"dead store|Assignment to Variable without Use ('Unused Variable')",
'770': "resource leak" ,
'114': "Process Control",
'121' :{'title': "Stack-based Buffer Overflow"},
'135' :"Incorrect Calculation of Multi-Byte String Length" ,
'126' :"Buffer Over-read",
'122' :{'title': "Heap-based Buffer Overflow"},
'123' :"Write-what-where Condition"  ,
'124' :{'title': "Buffer Underwrite ('Buffer Underflow')"},
'127' :{'title': "Buffer Under-read"},
'134': {'title': "Uncontrolled Format String"},
'15':" External Control of System or Configuration Setting ",
'176': "Improper Handling of Unicode Encoding",
'188': "Reliance on Data/Memory Layout",
'190' :{'title': "Integer Overflow or Wraparound"},
'191': {'title': "Integer Underflow (Wrap or Wraparound)"},
'194': {'title': "Unexpected Sign Extension"},
'195': {'title': "Signed to Unsigned Conversion Error"},
'196': "Unsigned to Signed Conversion Error",
'197': {'title': "Numeric Truncation Error"},
'222': "Truncation of Security-relevant Information",
'223' :"Omission of Security-relevant Information",
'226' :"Sensitive Information Uncleared Before Release",
'23' :{'title': "Relative Path Traversal"},
'242' :"Use of Inherently Dangerous Function",
'244' :"Improper Clearing of Heap Memory Before Release ('Heap Inspection')",
'247' :"DEPRECATED (Duplicate): Reliance on DNS Lookups in a Security Decision",
'253' :"Incorrect Check of Function Return Value",
'256' :"Plaintext Storage of a Password",
'259': "Use of Hard-coded Password",
'272': "Least Privilege Violation",
'273': "Improper Check for Dropped Privileges",
'284': "Improper Access Control",
'319': "Cleartext Transmission of Sensitive Information",
'321': "Use of Hard-coded Cryptographic Key",

'325': "Missing Required Cryptographic Step",
'327': "Use of a Broken or Risky Cryptographic Algorithm",
'328': "Reversible One-Way Hash"  ,
'338': "Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)",
'364': "Signal Handler Race Condition" ,
'366': "Race Condition within a Thread",
'367': "Time-of-check Time-of-use (TOCTOU) Race Condition",
'369': "Divide By Zero",
'36': {'title': "Absolute Path Traversal"} ,
'377' :"Insecure Temporary File",
'390' :"Detection of Error Condition Without Action",
'391': "Unchecked Error Condition",
'396': "Declaration of Catch for Generic Exception"  ,
'397': "Declaration of Throws for Generic Exception",
'398': "Indicator of Poor Code Quality",
'400': "Uncontrolled Resource Consumption ('Resource Exhaustion')",
'401': {'title': "Improper Release of Memory Before Removing Last Reference ('Memory Leak')"},
'404': "Improper Resource Shutdown or Release",
'415': "Double Free",
'416': "Use After Free",
'426': "Untrusted Search Path",
'427': "Uncontrolled Search Path Element",
'440': "Expected Behavior Violation",
'457': {'title': "Use of Uninitialized Variable"},
'459': "Incomplete Cleanup",
'464': "Addition of Data Structure Sentinel",
'467': "Use of sizeof() on a Pointer Type",
'468': "Incorrect Pointer Scaling",
'469': "Use of Pointer Subtraction to Determine Size",
'475': "Undefined Behavior for Input to API",
'478': "Missing Default Case in Switch Statement",
'479': "Signal Handler Use of a Non-reentrant Function",
'480': "Use of Incorrect Operator",
'481': "Assigning instead of Comparing",
'482': "Comparing instead of Assigning",
'483': "Incorrect Block Delimitation",
'484': "Omitted Break Statement in Switch",
'500': "Public Static Field Not Marked Final",
'506': "Embedded Malicious Code",
'510': "Trapdoor",
'511': "Logic/Time Bomb",
'526': "Information Exposure Through Environmental Variables",
'534': "Information Exposure Through Debug Log Files",
'535': "Information Exposure Through Shell Error Message",
'546': "Suspicious Comment",
'561': "Dead Code",
'562': "Return of Stack Variable Address",

'570': "Expression is Always False",
'571': "Expression is Always True",
'587': "Assignment of a Fixed Address to a Pointer",
'588': "Attempt to Access Child of a Non-structure Pointer" ,
'590': {'title': "Free of Memory not on the Heap"},
'591' :"Sensitive Data Storage in Improperly Locked Memory",
'605' :"Multiple Binds to the Same Port",
'606': {'title': "Unchecked Input for Loop Condition"},
'615': "Information Exposure Through Comments",
'617': "Reachable Assertion",
'620': "Unverified Password Change",
'665': "Improper Initialization",
'666': "Operation on Resource in Wrong Phase of Lifetime",
'667': "Improper Locking",
'672': "Operation on a Resource after Expiration or Release",
'674': "Uncontrolled Recursion",
'675': "Duplicate Operations on Resource ",
'676': "Use of Potentially Dangerous Function ",
'680': "Integer Overflow to Buffer Overflow ",
'681':" Incorrect Conversion between Numeric Types ",
'685': "Function Call With Incorrect Number of Arguments ",
'688': "Function Call With Incorrect Variable or Reference as Argument ",
'690': {'title': "Null Deref from Return"},
'758': "Reliance on Undefined, Unspecified, or Implementation-Defined Behavior",
'761': "Free of Pointer not at Start of Buffer",
'762': "Mismatched Memory Management Routines",
'773':" Missing Reference to Active File Descriptor or Handle",
'775': "Missing Release of File Descriptor or Handle after Effective Lifetime",
'780': "Use of RSA Algorithm without OAEP",
'785': "Use of Path Manipulation Function without Maximum-sized Buffer",
'789': "Uncontrolled Memory Allocation",
'78': {'title': "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')"},
'832': "Unlock of a Resource that is not Locked" ,
'835': "Loop with Unreachable Exit Condition ('Infinite Loop')",
'843': "Access of Resource Using Incompatible Type ('Type Confusion')",
'90': "Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')"
}